name: sgru
evaluate: true
cfg:
  optimizer: sgd
  lr: 0.001
  lr_decay_factor: 0.1  # Multiplicative learning rate decay factor. Leave empty if not using LR scheduling
  epochs_per_lr_decay: 2 # Number of epoch intervals before the decay factor is applied to LR. Leave empty if not using LR scheduling.
  momentum: 0.9
  weight_decay: 0.1
  use_l2_penalty: false
  epochs: 4
  recalc_freq: 1  # Frequency to recalculate forget subspace 
  num_components: 10  # Number of principal components to use 
  redirection_strength: 2.5  # Lambda value for gradient deflection 
  max_grad_norm: 10  #  Maximum gradient norm for clipping 