defaults:
  - _self_
  - model: ???
  - dataset: ???
  - attack: ???
seed: 42
verbose: true
visualise: true
# output_dir: ???
output_dir: ./artifactstest/galrt

# python src/attacks/GALRT/main.py dataset=cifar10 model=torchhub attack=attack

