load_method: class  
class_path: ./modelloadtest
class_name:  CIFAR10
Modeloriginal_model_ckpt_path: ???  # You must specify a path to the original model.
unlearned_model_ckpt_path: ???
model_kwargs:
