load_method: torchhub  
repo_path: chenyaofo/pytorch-cifar-models
model_name: cifar10_resnet20
original_model_ckpt_path: artifacts/models/unlearn/neggrad/cifar10_resnet20_42_original_005.pt
unlearned_model_ckpt_path: artifacts/models/unlearn/neggrad/cifar10_resnet20_42_unlearned_005.pt 
