init_method: torchhub  

init_path: chenyaofo/pytorch-cifar-models
init_name: cifar10_resnet20
model_ckpt_path:
model_kwargs:
  pretrained: true 

num_classes: 10

# Model saving and evaluation
output_dir: ./artifacts/models
save_name: