experiment:
  name: "test_config"
  original_weights: "/vol/bitbucket/vb524/safe-unlearning/src/artifacts/models/exp1_original.pth"
  unlearned_weights: "/vol/bitbucket/vb524/safe-unlearning/src/artifacts/unlearned/exp1_neggrad_0a_2ep_1f_1r.pth"
  output:
    dir: src/artifacts/

data:
  model_name: resnet18
  dataset_name: cifar10
  labels: [7]
  num_classes: 10 
  data_root: "/vol/bitbucket/oap24/final_project/safe-unlearning/src/unlearning/test_samples3"
  image_mean: [0.5, 0.5, 0.5]
  image_std: [0.5, 0.5, 0.5]
  image_size: [3, 32, 32]

reconstructor:
  type: inversegrad  # Options: ggl, inversegrad
  lr: 0.01
  GGL:
    num_updates: 1
    unlearning_method: neggrad
    alpha: None
    gamma: None
    min_epochs: None
    max_epochs: None
    batch_size: 1
    loss_models: "l2"  # 'l1', 'l2', 'weighted', or 'interpolated'
    budget: 500  # Budget for Bayesian Optimization
    search_dim: 128  # Dimension of the latent space
    use_tanh: false  # Whether to apply tanh activation to the latent vector
  InverseGrad:
    grad_diff_lr: 0.01
    signed: True
    boxed: True
    cost_fn: sim
    indices: def
    weights: equal
    optim: adamw
    num_runs: 1
    recon_iterations: 100
    total_variation: 1e-1
    init: randn
    lr_decay: True
    scoring_choice: loss
    eval: True
    filter: none

seed: 42
verbose: true

