experiment:
  name: "test_config"
  seed: 42
  model_name: resnet18
  device: "cuda"

paths:
  original_weights: "/vol/bitbucket/oap24/final_project/safe-unlearning/src/artifacts/unlearned/resnet18_unlearned_gascent_seed42_epoch1_sample1_01.pth"
  unlearned_weights: "/vol/bitbucket/oap24/final_project/safe-unlearning/src/artifacts/unlearned/resnet18_unlearned_gascent_seed42_epoch1_sample1_01.pth"
  
data:
  labels: [13]
  dataset_name: imagenet
  num_classes: 1000 
  data_root: "/vol/bitbucket/oap24/final_project/safe-unlearning/src/unlearning/test_samples3"
  image_mean: [0.5, 0.5, 0.5]
  image_std: [0.5, 0.5, 0.5]
  image_size: [3, 32, 32]
  batch_size: 1
  num_workers: 1

Reconstructor:
  type: inversegrad  # Options: ggl, inversegrad
  lr: 0.01
  GGL:
    num_classes: 1000 # think it would be good if we both have this parameter? 
    num_updates: 1
    unlearning_method: neggrad
    alpha: None
    gamma: None
    min_epochs: None
    max_epochs: None
    batch_size: 1
    loss_models: "l2"  # 'l1', 'l2', 'weighted', or 'interpolated'
    budget: 500  # Budget for Bayesian Optimization
    search_dim: 128  # Dimension of the latent space
    use_tanh: false  # Whether to apply tanh activation to the latent vector
  InverseGrad:
    grad_lr: 0.01
    rec_epochs: 10000
    num_images: 1
    signed: True
    boxed: False
    cost_fn: sim
    indices: def
    weights: equal
    optim: adamw
    num_runs: 1
    total_variation: 1e-1
    init: 'randn'
    lr_decay: True
    scoring_choice: loss

Unlearner:
  name: neggrad  # Options: neggrad, neggradplus, scrub, euk, cfk, finetune
  evaluate: true
  cfg:
    # Common parameters for all unlearners
    lr: 0.01
    weight_decay: 0
    use_l2_penalty: false
    epochs: 1 # Ignored for scrub
    # Specific parameters for some unlearners (will be ignored for others)
    beta: 0.5  # For neggradplus  beta = 0: forget only, beta = 1: retain only
    min_epochs: 2  # For scrub  retain aligning steps
    max_epochs: 5  # For scrub  forget away steps
    alpha: 0.5  # For scrub  retain loss; gamma: cross-entropy weight
    gamma: 0.5  # For scrub  retain loss; alpha: KL divergence weight
    k: 3  # For euk/cfk
    method: CFk  # For kunlearn (CFk or EUk)
    reinit_method: randn  # For euk (randn or zero or xaiver)


dataset_cfg:
  batch_sizes:
    retain: 1
    forget: 1
    val: 32
  save_path: ./data

output:
  dir: artifacts/
verbose: true