experiments:
- exp_name: neggrad_0.1a_1ep_1f_5r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0.1a_1ep_1f_5r.pth
  labels: [7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: &id001
  - 0.5
  - 0.5
  - 0.5
  image_shape: &id002
  - 3
  - 32
  - 32
  image_std: &id003
  - 0.5
  - 0.5
  - 0.5
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_4ep_32f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_4ep_32f_1r.pth
  labels: [7, 1, 0, 4, 7, 3, 3, 8, 5, 8, 2, 6, 5, 5, 7, 2, 8, 1, 1, 9, 8, 6, 1, 5,
         8, 2, 6, 4, 2, 4, 2, 9]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0.25a_1ep_1f_30r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0.25a_1ep_1f_30r.pth
  labels: [7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_1ep_16f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_1ep_16f_1r.pth
  labels: [7, 1, 0, 4, 7, 3, 3, 8, 5, 8, 2, 6, 5, 5, 7, 2]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_3ep_16f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_3ep_16f_1r.pth
  labels: [7, 1, 0, 4, 7, 3, 3, 8, 5, 8, 2, 6, 5, 5, 7, 2]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0.01a_1ep_5f_5r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0.01a_1ep_5f_5r.pth
  labels: [7, 1, 0, 4, 7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_1ep_1f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_1ep_1f_1r.pth
  labels: [7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_3ep_1f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_3ep_1f_1r.pth
  labels: [7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0.025a_1ep_5f_5r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0.025a_1ep_5f_5r.pth
  labels: [7, 1, 0, 4, 7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0.25a_1ep_5f_5r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0.25a_1ep_5f_5r.pth
  labels: [7, 1, 0, 4, 7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_1ep_2f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_1ep_2f_1r.pth
  labels: [7, 1]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_3ep_2f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_3ep_2f_1r.pth
  labels: [7, 1]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0.05a_1ep_2f_5r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0.05a_1ep_2f_5r.pth
  labels: [7, 1]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0.2a_1ep_2f_5r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0.2a_1ep_2f_5r.pth
  labels: [7, 1]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_1ep_32f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_1ep_32f_1r.pth
  labels: [7, 1, 0, 4, 7, 3, 3, 8, 5, 8, 2, 6, 5, 5, 7, 2, 8, 1, 1, 9, 8, 6, 1, 5,
         8, 2, 6, 4, 2, 4, 2, 9]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_4ep_1f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_4ep_1f_1r.pth
  labels: [7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0.05a_1ep_5f_5r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0.05a_1ep_5f_5r.pth
  labels: [7, 1, 0, 4, 7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0.5a_1ep_1f_30r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0.5a_1ep_1f_30r.pth
  labels: [7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_1ep_5f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_1ep_5f_1r.pth
  labels: [7, 1, 0, 4, 7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_4ep_2f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_4ep_2f_1r.pth
  labels: [7, 1]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0.1a_1ep_1f_10r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0.1a_1ep_1f_10r.pth
  labels: [7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0.5a_1ep_1f_5r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0.5a_1ep_1f_5r.pth
  labels: [7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_1ep_8f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_1ep_8f_1r.pth
  labels: [7, 1, 0, 4, 7, 3, 3, 8]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0.1a_1ep_1f_30r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0.1a_1ep_1f_30r.pth
  labels: [7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_2ep_16f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_2ep_16f_1r.pth
  labels: [7, 1, 0, 4, 7, 3, 3, 8, 5, 8, 2, 6, 5, 5, 7, 2]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_4ep_8f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_4ep_8f_1r.pth
  labels: [7, 1, 0, 4, 7, 3, 3, 8]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0.1a_1ep_1f_5r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0.1a_1ep_1f_5r.pth
  labels: [7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0.5a_2ep_1f_30r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0.5a_2ep_1f_30r.pth
  labels: [7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_2ep_1f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_2ep_1f_1r.pth
  labels: [7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_5ep_2f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_5ep_2f_1r.pth
  labels: [7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0.1a_1ep_2f_5r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0.1a_1ep_2f_5r.pth
  labels: [7, 1]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_2ep_2f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_2ep_2f_1r.pth
  labels: [7, 1]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_2ep_32f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_2ep_32f_1r.pth
  labels: [7, 1]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0.5a_3ep_1f_30r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0.5a_3ep_1f_30r.pth
  labels: [7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_5ep_5f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_5ep_5f_1r.pth
  labels: [7, 1, 0, 4, 7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0.1a_1ep_5f_5r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0.1a_1ep_5f_5r.pth
  labels: [7, 1, 0, 4, 7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0.5a_4ep_1f_30r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0.5a_4ep_1f_30r.pth
  labels: [7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0.25a_1ep_1f_10r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0.25a_1ep_1f_10r.pth
  labels: [7]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
- exp_name: neggrad_0a_2ep_8f_1r
  seed: 42
  original_weights_path: ../../artifacts/models/exp1_original.pth
  unlearned_weights_path: ../../artifacts/unlearned/exp1_neggrad_0a_2ep_8f_1r.pth
  labels: [7, 1, 0, 4, 7, 3, 3, 8]
  rec_experiments: 1
  rec_epochs: 10000
  rec_lr: 0.05
  grad_lr: 0.01
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  savepath: ../../artifacts/reconstructed/InverseGrad/
