type: ggl
lr: 0.01
unlearned_labels: ??
cfg:
  num_updates: 1
  unlearning_method: neggrad
  batch_size: 1
  loss_models: "l2"  # 'l1', 'l2', 'weighted', or 'interpolated'
  budget: 1000  # Budget for Bayesian Optimization
  search_dim: 128  # Dimension of the latent space
  use_tanh: false  # Whether to apply tanh activation to the latent vector
  gp_optim: "AdamW"
  use_scheduler: True
  initial_lr: 1
  initial_z_path: 
unlearner:
  alpha: None
  gamma: None
  min_epochs: None
  max_epochs: None
  weight_decay: 0
  use_l2_penalty: False
  optimizer: sgd
  momentum: 0
  sep_epochs: True
  lr_decay_factor: 
  epochs_per_lr_decay: 


