type: ggl  # Options: ggl, inversegrad
lr: 0.01
cfg:
  num_updates: 1
  unlearning_method: neggrad
  alpha: None
  gamma: None
  min_epochs: None
  max_epochs: None
  batch_size: 1
  loss_models: "l2"  # 'l1', 'l2', 'weighted', or 'interpolated'
  budget: 500  # Budget for Bayesian Optimization
  search_dim: 128  # Dimension of the latent space
  use_tanh: false  # Whether to apply tanh activation to the latent vector