type: invertgrad  # Options: ggl, invertgrad
lr: 0.05
unlearned_labels: # Optional: either pass in labels or num_images
cfg:   # attack-specific parameters
  num_images:        
  grad_diff_lr: 0.01
  signed: True
  boxed: True
  cost_fn: sim
  indices: def
  weights: equal
  optim: adamw
  num_runs: 1
  recon_iterations: 1000
  total_variation: 1e-2
  init: randn
  lr_decay: True
  scoring_choice: loss
  eval: True
  filter: none