name: cifar10
num_classes: 10
load_method: # The loading method of the dataset. Choices: torchvision/local
binaries_download_dir: # The directory to download the dataset binaries to
init_path: # the directory path where the original train or train/test dataset images can be found
save_path: ??? # the parent directory path for the train/val/test/forget/retain folders.
proportion: 1
val_ratio: 0.2
forget_ratio: 0.1
background_ratio: 0.1
cfg:
  batch_sizes:
    retain: 64
    forget: 64
    val: 64
  num_workers: 4