name: resnet18
num_classes: ???  # Must specify the number of classes in the dataset
original_model_ckpt_path: ???  # You must specify a path to the original model.
unlearned_model_ckpt_path: ???
output_dir: ???  # Path to save the model to