# Model Loading Configuration
load_method: torch  # Options: function, torch

init_path: chenyaofo/pytorch-cifar-models
init_name: cifar10_resnet20
weight_path: #./artifacts/models/reloaded/cifar10_resnet20_cifar10.pt
model_kwargs:
  # arg1: value1
  # arg2: value2
pretrained: true # Set to true to load with pretrained weights

# Model saving and evaluation
save_dir: ./artifacts/models
save_name:

validate: false  # Whether to validate the model after loading
model_eval: true  # Test the model 
batch_size: 128

# Dataset configuration
dataset: cifar10  # Options: cifar10, cifar100, imagenet
dataset_save_dir: ./data


wandb:
  enabled: true

seed: 42  