name: scrub
evaluate: true
cfg:
  optimizer: sgd
  lr: 0.0005
  lr_decay_factor: 0.1  # Multiplicative learning rate decay factor. Leave empty if not using LR scheduling
  epochs_per_lr_decay: 2 # Number of epoch intervals before the decay factor is applied to LR. Leave empty if not using LR scheduling.
  momentum: 0.9
  weight_decay: 0.1
  use_l2_penalty: false
  min_epochs: 0  # For scrub  retain aligning steps
  max_epochs: 2  # For scrub  forget away steps
  alpha: 0.5  # For scrub  retain loss; gamma: cross-entropy weight
  gamma: 0.5  # For scrub  retain loss; alpha: KL divergence weight
  sep_epochs: true