name: cifar10  # Options: cifar10, cifar5, cifar100, imagenet
num_classes: 10
save_path: ??? # the directory filepath where the dataset should be loaded in from. 
cfg:
  batch_sizes:
    retain: 128
    forget: 128
    val: 128
  num_workers: 4