name: cifar10  # Options: cifar10, cifar5, cifar100, imagenet
save_path: ??? # the directory filepath where the dataset should be loaded in from. 
cfg:
  batch_sizes:
    retain: 32
    forget: 32
    val: 32
  num_workers: 4