experiments:
- exp_name: resnet18_ga_1forget_1ep
  grad_lr: 0.05
  image_mean: &id001
  - 0.5
  - 0.5
  - 0.5
  image_shape: &id002
  - 3
  - 32
  - 32
  image_std: &id003
  - 0.5
  - 0.5
  - 0.5
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 1
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_ga_1forget_1ep.pth
- exp_name: resnet18_ga_1forget_5ep
  grad_lr: 0.05
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 1
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_ga_1forget_5ep.pth
- exp_name: resnet18_ga_1forget_10ep
  grad_lr: 0.05
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 1
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_ga_1forget_10ep.pth
- exp_name: resnet18_ga_2forget_1ep
  grad_lr: 0.05
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 2
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_ga_2forget_1ep.pth
- exp_name: resnet18_ga_2forget_5ep
  grad_lr: 0.05
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 2
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_ga_2forget_5ep.pth
- exp_name: resnet18_ga_2forget_10ep
  grad_lr: 0.05
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 2
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_ga_2forget_10ep.pth
- exp_name: resnet18_ga_5forget_1ep
  grad_lr: 0.05
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 5
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_ga_5forget_1ep.pth
- exp_name: resnet18_ga_5forget_5ep
  grad_lr: 0.05
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 5
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_ga_5forget_5ep.pth
- exp_name: resnet18_ga_10forget_5ep
  grad_lr: 0.05
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 10
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_ga_10forget_5ep.pth
- exp_name: resnet18_ga_10forget_10ep
  grad_lr: 0.05
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 10
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_ga_10forget_10ep.pth
- exp_name: resnet18_scrub_2forget_1ep
  grad_lr: 0.005
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 2
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_scrub_2forget_1ep.pth
- exp_name: resnet18_scrub_5forget_1ep
  grad_lr: 0.005
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 5
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_scrub_5forget_1ep.pth
- exp_name: resnet18_scrub_10forget_1ep
  grad_lr: 0.005
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 10
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_scrub_10forget_1ep.pth
- exp_name: resnet18_scrub_2forget_2ep
  grad_lr: 0.005
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 2
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_scrub_2forget_2ep.pth
- exp_name: resnet18_scrub_5forget_2ep
  grad_lr: 0.005
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 5
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_scrub_5forget_2ep.pth
- exp_name: resnet18_scrub_10forget_2ep
  grad_lr: 0.005
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 10
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_scrub_10forget_2ep.pth
- exp_name: resnet18_eval_ga_1forget_1ep
  grad_lr: 0.05
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 1
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_eval_ga_1forget_1ep.pth
- exp_name: resnet18_eval_ga_1forget_5ep
  grad_lr: 0.05
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 1
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_eval_ga_1forget_5ep.pth
- exp_name: resnet18_eval_ga_1forget_10ep
  grad_lr: 0.05
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 1
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_eval_ga_1forget_10ep.pth
- exp_name: resnet18_eval_ga_2forget_1ep
  grad_lr: 0.05
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 2
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_eval_ga_2forget_1ep.pth
- exp_name: resnet18_eval_ga_2forget_5ep
  grad_lr: 0.05
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 2
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_eval_ga_2forget_5ep.pth
- exp_name: resnet18_eval_ga_2forget_10ep
  grad_lr: 0.05
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 2
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_eval_ga_2forget_10ep.pth
- exp_name: resnet18_eval_ga_5forget_1ep
  grad_lr: 0.05
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 5
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_eval_ga_5forget_1ep.pth
- exp_name: resnet18_eval_ga_5forget_5ep
  grad_lr: 0.05
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 5
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_eval_ga_5forget_5ep.pth
- exp_name: resnet18_eval_ga_10forget_5ep
  grad_lr: 0.05
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 10
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_eval_ga_10forget_5ep.pth
- exp_name: resnet18_eval_ga_10forget_10ep
  grad_lr: 0.05
  image_mean: *id001
  image_shape: *id002
  image_std: *id003
  normalise: true
  num_classes: 10
  original_weights_path: ../../artifacts/models/resnet18_cifar10_10ep.pth
  rec_batch_size: 10
  rec_epochs: 300
  rec_experiments: 3
  rec_lr: 0.5
  savepath: ../../artifacts/reconstructed/DGL/
  unlearned_weights_path: ../../artifacts/unlearned/resnet18_eval_ga_10forget_10ep.pth
