params:
  num_classes: 10
  original_weights_path: ../../artifacts/models/cifar10_pretrained.pth
  unlearned_weights_path: ../../artifacts/unlearned/cifar10_pretrained_ga.pth
  rec_batch_size: 1
  rec_epochs: 300
  rec_lr: 0.01
  grad_lr: 0.001
  image_shape: [3,32,32]
  image_mean: [0,0,0]
  image_std: [1,1,1]
  normalise: False

  savepath: ../../artifacts/reconstructed/DGL/