dataset:
  name: cifar10
  save_path: ./data
  val_ratio: 0.2
  forget_ratio: 0.2

model:
  name: resnet18
  num_classes: 10
  pretrained: false

unlearner:
  name: neggradplus

attack:
  name: lira
  cfg:
    num_splits: 10
    num_forgets: 5

exp_name: lira_test_config
seed: 42
device: cpu
batch_size: 1024
num_workers: 4