model:
  name: resnet18
  num_classes: 10
  model_ckpt_path: # You must specify a path to the original model.
unlearner:
  name: neggradplus  # Options: neggrad, neggradplus, scrub, euk, cfk, finetune
  evaluate: true
  verbose: true
  cfg:
    # Common parameters for all unlearners
    loss_fn: cross_entropy
    lr: 0.001
    weight_decay: 0
    use_l2_penalty: false
    epochs: 5 # Ignored for scrub
    # Specific parameters for some unlearners (will be ignored for others)
    beta: 0.5  # For neggradplus  beta = 0: forget only, beta = 1: retain only
    min_epochs: 2  # For scrub  retain aligning steps
    max_epochs: 5  # For scrub  forget away steps
    alpha: 0.5  # For scrub  retain loss; gamma: cross-entropy weight
    gamma: 0.5  # For scrub  retain loss; alpha: KL divergence weight
    k: 3  # For euk/cfk
    method: CFk  # For kunlearn (CFk or EUk)
    reinit_method: randn  # For euk (randn or zero or xaiver)
dataset:
  name: cifar10  # Options: cifar10, cifar5, cifar100, imagenet
  url: # must end in .tar or .tar.gz
  save_path: ./data # the directory filepath where the dataset should be saved OR is saved and should be loaded in from.
  proportion: 1 # Choose 1 to get all data. Data will always be balanced.
  num_splits: 10
  num_forgets: 5
seed: 42
output_dir: artifacts/