model_loading: torchhub  
repo_path: chenyaofo/pytorch-cifar-models
model_name: cifar10_resnet20
original_model_ckpt_path: artifacts/models/unlearn/sgru/cifar10_resnet20_42_original.pt
unlearned_model_ckpt_path: artifacts/models/unlearn/sgru/cifar10_resnet20_42_unlearned.pt


# python src/unlearning/main.py dataset=cifar10 model=torchhub model.repo_path=chenyaofo/pytorch-cifar-models model.model_name=cifar10_resnet20 unlearner=neggradplus dataset.save_path=./data output_dir=./artifacts/models